### ISSUE TITLE
reserve a top-level `version` keyword in the yaml format, for future use

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#18] opened 2020-10-27 08:56 UTC
It's almost certain that we'll want to change the format in the future. We should anticipate this change.

**Comment by grahamgower** [comment] 2020-12-02 16:12
I don't think we actually need to do anything for this. Additional toplevel properties in the yaml file are currently ignored.

**Comment by jeromekelleher** [comment] 2021-01-13 10:10
Dupe of #20

**Closed by jeromekelleher** 2021-01-13 10:10 UTC
Labels: demes-python
